name: Build FlashInfer wheels

inputs:
  name:
    default: flashinfer
    type: string

  patches_version:
    default: ~
    type: string

  python_version:
    required: true
    type: string

  ref:
    default: main
    type: string

  repository:
    default: flashinfer-ai/flashinfer
    type: string

  version:
    default: ~
    type: string

runs:
  using: "composite"

  steps:
    - name: Normalize wheel name
      shell: bash
      run: echo WHEEL_NAME=${WHEEL_NAME/-/_} >> "$GITHUB_ENV"
      env:
        WHEEL_NAME: "${{ inputs.name }}"

    - name: Clear cache
      shell: bash
      run: rm -fr /opt/hostedtoolcache

    - name: Checkout ${{ inputs.repository }} (${{ inputs.ref }})
      uses: actions/checkout@v4
      with:
        ref: ${{ inputs.ref }}
        repository: ${{ inputs.repository }}
        path: ${{ env.WHEEL_NAME }}

    - if: inputs.patches_version != ''
      name: Apply patches (${{ inputs.patches_version }})
      uses: ./.github/actions/apply-patches
      with:
        name: ${{ env.WHEEL_NAME }}
        path: ${{ env.WHEEL_NAME }}
        version: ${{ inputs.patches_version }}

    - name: Resolve SOURCE_DATE_EPOCH
      shell: bash
      run: echo "SOURCE_DATE_EPOCH=$(git log -1 --format=%ct)" | tee "$GITHUB_ENV"

   - name: Setup build cache
      uses: ./.github/actions/setup-build-cache
      with:
        key: build-flashinfer

    - name: Build wheels
      uses: pypa/cibuildwheel@v2.18.0
      with:
        package-dir: ${{ env.WHEEL_NAME }}/python
      env:
        CIBW_BEFORE_ALL_LINUX: .github/actions/setup-build-cache/before_all.sh
        CIBW_BUILD: cp${{ inputs.python_version }}-manylinux_x86_64
        CIBW_BUILD_VERBOSITY: 1
        CIBW_CONTAINER_ENGINE: "docker; create_args: --volume /home/runner/.cache:/root/.cache:rw"
        CIBW_ENVIRONMENT: >
          TORCH_CUDA_ARCH_LIST=6.1
        CIBW_ENVIRONMENT_PASS_LINUX: >
          ACTIONS_CACHE_URL
          ACTIONS_RUNTIME_TOKEN
          SCCACHE_DIRECT
          SCCACHE_GHA_ENABLED
        CIBW_MANYLINUX_PYPY_X86_64_IMAGE: quay.io/pypa/manylinux2014_x86_64:latest
        CIBW_MANYLINUX_X86_64_IMAGE: quay.io/pypa/manylinux2014_x86_64:latest

    - name: Repackage wheels
      uses: ./.github/actions/repackage-wheels
      with:
        name: ${{ env.WHEEL_NAME }}
        version: ${{ inputs.wheel_version }}

    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: ${{ env.WHEEL_NAME }}
        path: wheelhouse/*.whl
