name: Build vLLM wheels

inputs:
  ref:
    default: main
    type: string

  repository:
    default: vllm-project/vllm
    type: string

runs:
  using: "composite"

  steps:
    - name: Checkout ${{ inputs.repository }} (${{ inputs.ref }})
      uses: actions/checkout@v4
      with:
        ref: ${{ inputs.ref }}
        repository: ${{ inputs.repository }}
        path: ${{ inputs.repository }}/${{ inputs.ref }}

    - name: Apply patches
      uses: ./.github/actions/common/apply-patches
      with:
        ref: ${{ inputs.ref }}
        repository: ${{ inputs.repository }}

    - name: Login to GitHub Container Registry
      uses: docker/login-action@v3
      with:
        password: ${{ env.GITHUB_TOKEN }}
        registry: ghcr.io
        username: ${{ github.actor }}

    - name: Expose ACTIONS_CACHE_URL and ACTIONS_RUNTIME_TOKEN
      uses: actions/github-script@v7
      with:
        script: |
          core.exportVariable("ACTIONS_CACHE_URL", process.env["ACTIONS_CACHE_URL"])
          core.exportVariable("ACTIONS_RUNTIME_TOKEN", process.env["ACTIONS_RUNTIME_TOKEN"])

    - name: Build
      uses: docker/build-push-action@v6
      with:
        context: ${{ inputs.repository }}/${{ inputs.ref }}
        network: host
        push: false
        tags: ghcr.io/${{ github.repository }}/vllm:${{ inputs.ref }}
        target: build

        build-args: |
          ACTIONS_CACHE_URL=${{ env.ACTIONS_CACHE_URL }}
          ACTIONS_RUNTIME_TOKEN=${{ env.ACTIONS_RUNTIME_TOKEN }}
          SCCACHE_GHA_ENABLED=1
          USE_SCCACHE=1
          torch_cuda_arch_list=6.0 6.1 7.0 7.5 8.0 8.6 8.9 9.0+PTX

        outputs: |
          type=local,dest=build

    - name: Copy wheel files
      shell: bash
      run: mv build/dist . && rm -r build

    - name: Build and push
      uses: docker/build-push-action@v6
      with:
        context: ${{ inputs.repository }}/${{ inputs.ref }}
        network: host
        push: true
        tags: ghcr.io/${{ github.repository }}/vllm:${{ inputs.ref }}
        target: vllm-openai

        build-args: |
          ACTIONS_CACHE_URL=${{ env.ACTIONS_CACHE_URL }}
          ACTIONS_RUNTIME_TOKEN=${{ env.ACTIONS_RUNTIME_TOKEN }}
          SCCACHE_GHA_ENABLED=1
          USE_SCCACHE=1
          torch_cuda_arch_list=6.0 6.1 7.0 7.5 8.0 8.6 8.9 9.0+PTX
