name: Build vLLM wheels

inputs:
  docker_latest:
    default: false
    type: boolean

  docker_token:
    default: ~
    type: string

  ref:
    default: main
    type: string

  repository:
    default: vllm-project/vllm
    type: string

runs:
  using: "composite"

  steps:
    - name: Cleanup runner image
      uses: ./.github/actions/common/runner-cleanup

    - name: Expose cache environment variables
      uses: ./.github/actions/common/expose-cache-vars

    - name: Checkout ${{ inputs.repository }} (${{ inputs.ref }})
      uses: actions/checkout@v4
      with:
        ref: ${{ inputs.ref }}
        repository: ${{ inputs.repository }}
        path: ${{ inputs.repository }}/${{ inputs.ref }}

    - name: Apply patches
      uses: ./.github/actions/common/apply-patches
      with:
        ref: ${{ inputs.ref }}
        repository: ${{ inputs.repository }}

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - if: inputs.docker_token != ''
      name: Login to GitHub Container Registry
      uses: docker/login-action@v3
      with:
        password: ${{ inputs.docker_token }}
        registry: ghcr.io
        username: ${{ github.repository_owner }}

    - name: Generate image tags
      uses: actions/github-script@v7
      with:
        script: |
          // Variable to store image tags
          const tags = [];

          // Add ref to tags
          tags.push(`ghcr.io/${context.repo.owner}/vllm:${core.getInput('ref')}`);

          // If this image marked as latest
          if (core.getBooleanInput('ghcr_latest')) {
            // Add latest to tags
            tags.push(`ghcr.io/${context.repo.owner}/vllm:latest`);
          }

          // Export image tags
          core.exportVariable('IMAGE_TAGS', tags.join(' '));

    - name: Build
      uses: docker/build-push-action@v6
      with:
        cache-from: type=gha
        cache-to: type=gha,mode=max
        context: ${{ inputs.repository }}/${{ inputs.ref }}
        network: host
        outputs: type=tar,dest=build.tar
        push: false
        tags: ${{ env.IMAGE_TAGS }}
        target: build

        build-args: |
          ACTIONS_CACHE_URL=${{ env.ACTIONS_CACHE_URL }}
          ACTIONS_RUNTIME_TOKEN=${{ env.ACTIONS_RUNTIME_TOKEN }}
          SCCACHE_GHA_ENABLED=1
          USE_SCCACHE=1
          torch_cuda_arch_list=6.0 6.1 7.0 7.5 8.0 8.6 8.9 9.0+PTX
          max_jobs=2
          nvcc_threads=2

    - name: Copy wheel files
      shell: bash
      run: tar --extract --file=build.tar --strip-components=1 workspace/dist && rm build.tar

    - name: Repackage wheels
      uses: ./.github/actions/common/repackage-wheels
      with:
        name: vllm_pascal
        tags: cp38-abi3-linux_x86_64
        path: dist/*.whl

    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: vllm_pascal
        path: dist/*.whl

    - if: inputs.docker_token != ''
      name: Build and push
      uses: docker/build-push-action@v6
      with:
        cache-from: type=gha
        cache-to: type=gha,mode=max
        context: ${{ inputs.repository }}/${{ inputs.ref }}
        network: host
        push: true
        tags: ${{ env.IMAGE_TAGS }}
        target: vllm-openai

        build-args: |
          ACTIONS_CACHE_URL=${{ env.ACTIONS_CACHE_URL }}
          ACTIONS_RUNTIME_TOKEN=${{ env.ACTIONS_RUNTIME_TOKEN }}
          SCCACHE_GHA_ENABLED=1
          USE_SCCACHE=1
          torch_cuda_arch_list=6.0 6.1 7.0 7.5 8.0 8.6 8.9 9.0+PTX
          max_jobs=2
          nvcc_threads=2
