name: Build vLLM wheels

inputs:
  ghcr_token:
    default: ~
    type: string

  ref:
    default: main
    type: string

  repository:
    default: vllm-project/vllm
    type: string

runs:
  using: "composite"

  steps:
    - name: Cleanup runner image
      uses: ./.github/actions/common/runner-cleanup

    - name: Expose cache environment variables
      uses: ./.github/actions/common/expose-cache-vars

    - name: Checkout ${{ inputs.repository }} (${{ inputs.ref }})
      uses: actions/checkout@v4
      with:
        ref: ${{ inputs.ref }}
        repository: ${{ inputs.repository }}
        path: ${{ inputs.repository }}/${{ inputs.ref }}

    - name: Apply patches
      uses: ./.github/actions/common/apply-patches
      with:
        ref: ${{ inputs.ref }}
        repository: ${{ inputs.repository }}

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - if: inputs.ghcr_token != ''
      name: Login to GitHub Container Registry
      uses: docker/login-action@v3
      with:
        password: ${{ inputs.ghcr_token }}
        registry: ghcr.io
        username: ${{ github.repository_owner }}

    - name: Build
      uses: docker/build-push-action@v6
      env:
        DOCKER_BUILD_RECORD_UPLOAD: false
      with:
        cache-to: type=local,dest=/var/tmp/buildx-cache,mode=max
        context: ${{ inputs.repository }}/${{ inputs.ref }}
        network: host
        outputs: type=tar,dest=build.tar
        push: false
        tags: ghcr.io/${{ github.repository_owner }}/vllm:${{ inputs.ref }}
        target: build

        build-args: |
          USE_SCCACHE=1
          torch_cuda_arch_list=6.0 6.1 7.0 7.5 8.0 8.6 8.9 9.0+PTX
          max_jobs=2
          nvcc_threads=2

        secrets: |
          ACTIONS_CACHE_URL=${{ env.ACTIONS_CACHE_URL }}
          ACTIONS_RUNTIME_TOKEN=${{ env.ACTIONS_RUNTIME_TOKEN }}

    - name: Copy wheel files
      shell: bash
      run: tar --extract --file=build.tar --strip-components=1 workspace/dist && rm build.tar

    - name: Repackage wheels
      uses: ./.github/actions/common/repackage-wheels
      with:
        name: vllm_pascal
        path: dist/*.whl

    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: vllm_pascal
        path: dist/*.whl

    - if: inputs.ghcr_token != ''
      name: Build and push
      uses: docker/build-push-action@v6
      env:
        DOCKER_BUILD_RECORD_UPLOAD: false
      with:
        cache-from: type=local,src=/var/tmp/buildx-cache
        context: ${{ inputs.repository }}/${{ inputs.ref }}
        network: host
        push: true
        tags: ghcr.io/${{ github.repository_owner }}/vllm:${{ inputs.ref }}
        target: vllm-openai

        build-args: |
          USE_SCCACHE=1
          torch_cuda_arch_list=6.0 6.1 7.0 7.5 8.0 8.6 8.9 9.0+PTX
          max_jobs=2
          nvcc_threads=2

        secrets: |
          ACTIONS_CACHE_URL=${{ env.ACTIONS_CACHE_URL }}
          ACTIONS_RUNTIME_TOKEN=${{ env.ACTIONS_RUNTIME_TOKEN }}
