name: Start `sccache-dist server`

runs:
  using: "composite"

  steps:
    - name: Execute `tailscale` command
      shell: bash
      run: scripts/tailscale.sh up --authkey=${{ env.TS_AUTH_KEY }} --hostname=${{ env.TS_HOSTNAME }} --ssh

    - name: Install `bubblewrap`
      shell: bash
      run: scripts/bubblewrap.sh

    - name: Install `sccache-dist`
      shell: bash
      run: scripts/sccache_dist.sh

    - name: Start `sccache-dist server`
      shell: bash
      run: scripts/sccache_dist_server.sh

    - if: always()
      name: Execute `tailscale` command
      shell: bash
      run: scripts/tailscale.sh logout
