name: sccache server

runs:
  using: "composite"

  steps:
    - name: Install common dependencies
      shell: bash
      run: scripts/common_dependencies.sh

    - name: Join the Tailscale network
      shell: bash
      run: sudo tailscale up --authkey=$TS_AUTH_KEY --hostname=$TS_HOSTNAME --ssh

    - name: Start `sccache-dist server`
      shell: bash
      run: scripts/sccache_dist_server.sh

    - if: always()
      name: Log out from Tailscale
      shell: bash
      run: sudo tailscale logout
