name: sccache client (post)

runs:
  using: "composite"

  steps:
    - if: always()
      name: Teardown `sccache` servers
      shell: bash
      run: scripts/sccache_teardown.sh

    - if: always()
      name: Log out from Tailscale
      shell: bash
      run: sudo tailscale logout
