version: 2.1

parameters:
  flashinfer:
    type: boolean
    default: false

commands:
  ghr:
    parameters:
      args:
        type: string

      tag:
        type: string

      path:
        type: string

    steps:
      - run:
          name: Install ghr
          command: go get github.com/tcnksm/ghr

      - run:
          name: Upload artifacts
          command: >
            ghr
            -t ${GITHUB_TOKEN}
            -u ${CIRCLE_PROJECT_USERNAME}
            -r ${CIRCLE_PROJECT_REPONAME}
            -c ${CIRCLE_SHA1}
            << parameters.args >>
            << parameters.tag >>
            << parameters.path >>

jobs:
  build-flashinfer:
    resource_class: 2xlarge+

    docker:
      - image: cimg/base:current

    steps:
      - run:
          name: Clone repository
          command: git clone --branch pascal-pkgs-ci --recursive --shallow -- https://github.com/sasha0552/flashinfer.git .

      - run:
          name: Build FlashInfer
          command: scripts/run-ci-build-wheel.sh
          environment:
            FLASHINFER_BUILD_VERSION: 0.1.6
            FLASHINFER_CI_CUDA_VERSION: 12.1
            FLASHINFER_CI_PYTHON_VERSION: 3.11
            FLASHINFER_CI_TORCH_VERSION: 2.4
            TORCH_CUDA_ARCH_LIST: 6.1

      - ghr:
          args: -replace
          tag: wheels
          path: dist

workflows:
  flashinfer:
    when: << pipeline.parameters.flashinfer >>

    jobs:
      - build-flashinfer
