name: Apply patches

inputs:
  ref:
    type: string

  repository:
    type: string

runs:
  using: "composite"

  steps:
    - name: Apply patches
      shell: bash
      run: |
        # Exit on error
        set -e

        # Constants
        readonly PATCHES_PATH="$PWD/patches/${{ inputs.repository }}/${{ inputs.ref }}"

        # Go to target directory
        cd "${{ inputs.repository }}/${{ inputs.ref }}"

        # If patches exists
        if [ -d "$PATCHES_PATH" ]; then
          # Apply patches
          for patch in "$PATCHES_PATH"/*; do
            # Apply patch
            if [[ "$patch" == *.patch ]]; then
              # Log patch name
              echo "Applying patch $patch..."

              # Apply
              patch --strip=1 < "$patch"
            fi

            # Apply script
            if [[ "$patch" == *.sh ]]; then
              # Log script name
              echo "Applying script $patch..."

              # Apply
              bash "$patch"
            fi
          done
        fi
