name: Expose cache environment variables

runs:
  using: "composite"

  steps:
    - name: Expose ACTIONS_CACHE_URL and ACTIONS_RUNTIME_TOKEN
      uses: actions/github-script@v7
      with:
        script: |
          core.exportVariable("ACTIONS_CACHE_URL", process.env["ACTIONS_CACHE_URL"])
          core.exportVariable("ACTIONS_RUNTIME_TOKEN", process.env["ACTIONS_RUNTIME_TOKEN"])
