name: Cleanup runner image

runs:
  using: "composite"

  steps:
    - name: Cleanup runner image
      shell: bash
      run: |
        # Remove unnecessary directories
        sudo rm -fr /opt/*
        sudo rm -fr /usr/lib/jvm
        sudo rm -fr /usr/lib/google-cloud-sdk
        sudo rm -fr /usr/local
        sudo rm -fr /usr/share/swift
        sudo rm -fr /usr/share/dotnet
        sudo rm -fr /usr/share/miniconda

        # Recreate directories
        sudo mkdir -p /usr/local/{bin,etc,games,include,lib,man,sbin,share,src}
