name: Setup build cache

inputs:
  key:
    required: true
    type: string

runs:
  using: "composite"

  steps:
    - name: Setup cache
      uses: actions/cache@v4
      with:
        key: ${{ inputs.key }}
        save-always: true

        path: |
          ~/.cache/pip

    - name: Set sccache environment variables
      shell: bash
      run: |
        echo "SCCACHE_GHA_ENABLED=1" | tee "$GITHUB_ENV"
        echo "SCCACHE_DIRECT=1" | tee "$GITHUB_ENV"

    - name: Install sccache
      uses: mozilla-actions/sccache-action@v0.0.5
