name: Setup build cache

runs:
  using: "composite"

  steps:
    - name: Setup cache
      uses: actions/cache@v3
      with:
        path: |
          /root/.cache/pip

    - name: Set SCCACHE_GHA_ENABLED
      shell: bash
      run: echo "SCCACHE_GHA_ENABLED=1" | tee "$GITHUB_ENV"

    - name: Install sccache
      uses: mozilla-actions/sccache-action@v0.0.5
