name: Setup build cache

runs:
  using: "composite"

  steps:
    - name: Set environment variables
      shell: bash
      run: |
        echo "SCCACHE_GHA_ENABLED=1" | tee -a "$GITHUB_ENV"
        echo "SCCACHE_DIRECT=1"      | tee -a "$GITHUB_ENV"

    - name: Install sccache
      uses: mozilla-actions/sccache-action@v0.0.5
