name: sccache client

runs:
  using: "composite"

  steps:
    - name: Cleanup runner image
      uses: ./.github/actions/common/runner-cleanup

    - name: Install common dependencies
      shell: bash
      run: scripts/common_dependencies.sh

    - name: Join the Tailscale network
      shell: bash
      run: sudo tailscale up --authkey=$TS_AUTH_KEY --hostname=$TS_HOSTNAME --ssh

    - name: Configure Docker daemon
      shell: bash
      run: scripts/tailscale_docker.sh

    - name: Start `sccache-dist scheduler`
      shell: bash
      run: scripts/sccache_dist_scheduler.sh

    - name: Wait for all servers
      shell: bash
      run: scripts/sccache_sync.sh
