name: sccache client

runs:
  using: "composite"

  steps:
    - name: Execute `tailscale` command
      shell: bash
      run: scripts/tailscale.sh up --authkey=$TS_AUTH_KEY --hostname=$TS_HOSTNAME --ssh

    - name: Configure Docker daemon
      shell: bash
      run: scripts/tailscale_docker.sh

    - name: Install `sccache-dist`
      shell: bash
      run: scripts/sccache_dist.sh

    - name: Start `sccache-dist scheduler`
      shell: bash
      run: scripts/sccache_dist_scheduler.sh

    - name: Wait for all servers
      shell: bash
      run: scripts/sccache_sync.sh
