name: "[Distributed] Build FlashInfer"

jobs:
  sccache-client:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Configure `sccache` client
        uses: ./.github/actions/sccache-client
        env:
          SCCACHE_SCHEDULER_HOSTNAME: ppc-${{ inputs.random }}-scheduler
          TS_AUTH_KEY: ${{ secrets.TS_AUTH_KEY }}
          TS_HOSTNAME: ppc-${{ inputs.random }}-client

  sccache-server:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Start `sccache-dist server`
        uses: ./.github/actions/sccache-server
        env:
          SCCACHE_SCHEDULER_HOSTNAME: ppc-${{ inputs.random }}-scheduler
          TS_AUTH_KEY: ${{ secrets.TS_AUTH_KEY }}
          TS_HOSTNAME: ppc-${{ inputs.random }}-server-${{ matrix.no }}

    strategy:
      matrix:
        no: [0, 1, 2, 3, 4, 5, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18]

  sccache-scheduler:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Start `sccache-dist scheduler`
        uses: ./.github/actions/sccache-scheduler
        env:
          TS_AUTH_KEY: ${{ secrets.TS_AUTH_KEY }}
          TS_HOSTNAME: ppc-${{ inputs.random }}-scheduler

on:
  workflow_dispatch:
    inputs:
      random:
        required: true
        type: string
