name: "[X] Build Triton (v3.0.0)"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Build Triton wheels
        uses: ./.github/actions/build-triton
        with:
          python_version: ${{ matrix.python_version }}
          ref: 55a4ab051c88ba2baa031e520a339d3fded6468f

    strategy:
      matrix:
        python_version:
          - "38"
          - "39"
          - "310"
          - "311"
          - "312"

  publish:
    needs: build
    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Publish wheels
        uses: ./.github/actions/common/publish-wheels
        with:
          prefix: triton_pascal-3.0.0-

  update-index:
    needs: publish
    runs-on: ubuntu-latest
    uses: ${{ github.repository }}/.github/workflows/zz-update-index.yml@main

on:
  workflow_dispatch:
