name: "[P] Build Triton 3.0.0 wheels"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Build Triton wheels
        uses: ./.github/actions/build-triton
        with:
          name: triton-pascal
          patches_version: 3.0.0
          python_version: ${{ matrix.python_version }}
          ref: 55a4ab051c88ba2baa031e520a339d3fded6468f

    strategy:
      matrix:
        python_version:
          - "38"
          - "39"
          - "310"
          - "311"
          - "312"

  publish:
    needs: build
    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Publish wheels
        uses: ./.github/actions/publish-wheels
        with:
          prefix: triton_pascal-3.0.0-

on:
  workflow_dispatch:
