name: "[X] Build vLLM (v0.6.1)"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Build vLLM wheels
        uses: ./.github/actions/build-vllm
        with:
          docker_token: ${{ secrets.GHCR_TOKEN }}
          ref: v0.6.1

  publish:
    needs: build
    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Publish wheels
        uses: ./.github/actions/common/publish-wheels
        with:
          prefix: vllm_pascal-0.6.1-

  update-index:
    needs: publish
    runs-on: ubuntu-latest
    uses: ./.github/workflows/zz-update-index.yml

on:
  workflow_dispatch:
