name: "[P] Build vLLM wheels"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Build vLLM wheels
        uses: ./.github/actions/build-vllm
        with:
          name: vllm-pascal
          patches_version: main

  publish:
    needs: build
    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Publish wheels
        uses: ./.github/actions/publish-wheels
        with:
          prefix: vllm_pascal-

on:
  push:
    paths:
      - .github/actions/build-vllm/**
      - .github/workflows/vllm-pascal-recurrent.yml
      - patches/vllm_pascal/main/**

  schedule:
    - cron: "30 1 * * *"

  workflow_dispatch:
