name: "[P] Build vLLM wheels (manual)"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Build vLLM wheels
        uses: ./.github/actions/build-vllm
        with:
          name: vllm-pascal
          patches_version: main
          ref: ${{ inputs.ref }}
          repository: ${{ inputs.repository }}

  publish:
    needs: build
    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Publish wheels
        uses: ./.github/actions/publish-wheels
        with:
          prefix: vllm_pascal-

on:
  workflow_dispatch:
    inputs:
      ref:
        default: main
        type: string

      repository:
        default: vllm-project/vllm
        type: string
