name: "[R] Build vLLM (main)"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Build vLLM wheels
        uses: ./.github/actions/build-vllm
        with:
          ref: main

on:
  schedule:
    - cron: "0 0 * * *"

  workflow_dispatch:
