name: "[X] Build vLLM (v0.6.0)"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Build vLLM wheels
        uses: ./.github/actions/build-vllm
        with:
          ref: v0.6.0
          ghcr_token: ${{ secrets.GHCR_TOKEN }}

  publish:
    needs: build
    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Publish wheels
        uses: ./.github/actions/common/publish-wheels
        with:
          prefix: vllm_pascal-0.6.2-

on:
  workflow_dispatch:
